### ISSUE TITLE
dva创建ROUTE或MODEL时报错

### ISSUE THREAD

**Issue by zhwb36** [dvajs/dva#1007]
环境：
nodejs: 6.11
dva : 0.7.8

执行 dva g route users  报如下错误：

TypeError: root.findRouters(...).getRouterInfo is not a function
    at transform (C:\Users\ZWB\AppData\Roaming\npm\node_modules\dva-cli\node_modules\dva-ast\lib\transform.js:42:32)
    at exports.default (C:\Users\ZWB\AppData\Roaming\npm\node_modules\dva-cli\node_modules\dva-ast\lib\api\index.js:46:36)
    at C:\Users\ZWB\AppData\Roaming\npm\node_modules\dva-cli\lib\generate.js:92:27
    at generate (C:\Users\ZWB\AppData\Roaming\npm\node_modules\dva-cli\lib\generate.js:108:11)
    at Object.<anonymous> (C:\Users\ZWB\AppData\Roaming\npm\node_modules\dva-cli\bin\dva-generate:11:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by kyawsithu** [comment]
I have same error Windows 10. Please answer us when can we expect to see the solution.

**Comment by thomas-ye** [comment]
我也是在 Windows 10遇到同样的问题，node版本是6.11.0.

**Comment by haireggs** [comment]
同样的问题
Windows 10,
node v8.1.2 ,
dva 0.7.8

**Comment by CaffreySun** [comment]
同样的问题
MacOS 10.12.5
node v8.1.2
dva 0.7.8

**Comment by kylezhang** [comment]
同上#1033

**Comment by wenris** [comment]
将全局安装库 **jscodeshift** 降级至 *0.3.28* 版本，或直接修改全局安装库 **dva-ast** 的文件，将下面文件中的 `'jscodeshift/dist/Collection';` 改为 `'jscodeshift/src/Collection';` ：

1. dva-ast/lib/collections/Entry.js
2. dva-ast/lib/collections/RouteComponent.js
3. dva-ast/lib/collections/Router.js

详见 https://github.com/dvajs/dva-cli/issues/91
