### ISSUE TITLE
effects yield race 无效

### ISSUE THREAD

**Issue by neewbee** [dvajs/dva#1028]
需要轮询 但是取消请求无效。麻烦看一下。

```javascript
effects:{
    *pollData({ id }, { call, put }) {
          try {
            yield call(service.delay, 3000);    
            yield put({ type: "fetchProgress", id });
          } catch (error) {
            return;
          } 
    },
    *watchPolling({ id }, { take, race }) {
          while (true) {
              yield take("fetchDone");  
              yield race([put({ type: "pollData", id }), take("cancelPolling")]); //doesn't work
          }
        },
    *watchCancel({}, { take }) {
          yield take("cancelPolling");
              console.info("cancel Taken") //works
     },
    *fetchInfo({ id }, { call, put }) {
          const info = yield call(service.fetchInfo, {id});
          const { err } = info;
          if (!err) {             
             yield put({ type: "fetchDone", info });
          }
    },
    *startPolling({ id }, { put }) {  
          yield put({ type: "watchPolling", id });
          yield put({ type: "watchCancel"});
          yield put({ type: "fetchInfo", id });
    }
},
subscriptions: {
    setup({ dispatch, history }) {
        return [history.listen(({ pathname, query }) => {
            if (pathname === "/users") {
                dispatch({ type: "startPolling", id: 1 });
            }
      }), history.listenBefore(( ) => {     
          dispatch({ type: "cancelPolling" });      
      })];
    }
}
```

**Comment by nihgwu** [comment]
如果你需要take，应该用 `watch`, dva 默认创建的是 `takeLatest`
可以参考下我这段代码 https://github.com/nihgwu/react-native-dva-starter/blob/master/app/models/router.js#L24-L40

**Comment by neewbee** [comment]
@nihgwu 感谢回复，默认应该是takeEvery？
[https://github.com/dvajs/dva/blob/master/src/createDva.js#L422](url)
[https://github.com/dvajs/dva/issues/7#issue-164651044](url)

我用如下方式：
```javscript
effects{
   *pollData({ id }, { call, put }) {
          try {
            yield call(service.delay, 3000);    
            yield put({ type: "fetchProgress", id });
          } catch (error) {
            return;
          } 
    },
  watch: [
      function* watchPollData({ userId = {} }, { take, put, race }) {
        while (true) {
          console.log("in true");
          yield take("fetchProgressOK");
          console.log("=======TAKE fetchProgressOK===========");

          yield race([take("cancelPolling"), put({ type: "pollData", userId })]); //dosen't work
        }
      },
      { type: "watcher" }
    ],
  ...
}
```
或者
```javascript
，['watchPollData']:[function*({ userId = {} }, { take, race }) {
      while (true) {
              yield take("fetchDone");  
              yield race([put({ type: "pollData", id }), take("cancelPolling")]); //doesn't work
          }
    },
      { type: "watcher" }
      ]
，
```
会报错
```javascript
TypeError: Cannot read property 'take' of undefined
    at watchPollData (eval at <anonymous> (http://localhost:8000/2.async.js:71:2), <anonymous>:247:24)
    at sagaWithCatch$ (http://localhost:8000/roadhog.dll.js:143841:32)
    at tryCatch (http://localhost:8000/roadhog.dll.js:144114:41)
    at Generator.invoke [as _invoke] (http://localhost:8000/roadhog.dll.js:144352:23)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8000/roadhog.dll.js:144166:22)
    at next (http://localhost:8000/roadhog.dll.js:147144:28)
    at proc (http://localhost:8000/roadhog.dll.js:147103:4)
    at runForkEffect (http://localhost:8000/roadhog.dll.js:147380:20)
    at runEffect (http://localhost:8000/roadhog.dll.js:147267:578)
    at next (http://localhost:8000/roadhog.dll.js:147148:10)

```

**Comment by nihgwu** [comment]
是 takeEvery，我写错了

**Comment by nihgwu** [comment]
仔细看我的例子， 如果是 watch， 是没有第一个参数的

**Comment by nihgwu** [comment]
不过我不是很明白为什么你要自己写 watcher，除非特殊情况，基本不用自己写 take 的，dva 的 effects 本身就是 take

**Comment by neewbee** [comment]
我对saga理解还不怎么透彻。是这样：我想实现页面加载的时候轮询，跳转到其他页面的时候取消。不知道我代码思路对不对。

**Comment by yanthink** [comment]
watchPollData: [function* ({ take, race }) {
 //
}, { type: 'watcher' }],

**Comment by neewbee** [comment]
I wonder if anybody could come up with a better solution

```javascript
*pollData({ userId = 1 }, { call, put }) {
  function delay(millis) {
    const promise = new Promise(resolve => {
      setTimeout(() => resolve(true), millis);
    });
    return promise;
  }
  try {
    yield call(delay, 2000);
    yield put({ type: "fetch", payload: { page: 1 } });
  } catch (error) {
    // cancellation error -- can handle this if you wish
  }
},
*cancelPolling({}, { put }) {
  yield put({ type: "fetchDataEnd" });
  yield put({ type: "cancelPollingAction", payload: { test: 1 } });
},
*fetch({ payload: { page = 1 } }, { call, put }) {
  const { data, headers } = yield call(usersService.fetch, { page });
  yield put({ type: "fetchDataEnd" });
},
watchPollData: [
  function*({ take, call, race, put }) {
    function delay(millis) {
      return new Promise(resolve => {
        setTimeout(() => resolve(true), millis);
      });
    }
    while (true) {
      yield take("fetchDataEnd");
      const raceResult = yield race([
        call(delay, 2000),
        take("cancelPollingAction")
      ]);
      // raceResult is either
      // {1: {"payload":{type:""cancelPollingAction""}}
      // or
      // { 0:true }
      // when we yield the second result,continue polling
      // meaning raceResult[1] would be undefined
      if (!raceResult[1]) {
        yield put({ type: "pollData" });
      }
    }
  },
  { type: "watcher" }
]
```

**Comment by conechan** [comment]
My solution

```js
  effects: {
    * fetchList ({ payload }, { call, put }) {
      const { data: { list } } = yield call(getList, payload)
      yield put({
        type: 'updateList',
        payload: Array.isArray(list) ? list : []
      })
    },
    stopPoll () {},
    startPoll: [
      function * ({ take, put, call, race }) {
        while (true) {
          const { payload } = yield take('startPoll')

          yield race([
            call(function * () {
              while (true) {
                yield put({ type: 'fetchList', payload })
                yield call(delay, 2000)
              }
            }),
            take('stopPoll')
          ])
        }
      },
      { type: 'watcher' }
    ]
  }
```
