### ISSUE TITLE
用户管理的 CURD Demo: dva g route users TypeError

### ISSUE THREAD

**Issue by EthanOrange** [dvajs/dva#1058]
node: 8.1.2
npm: 5.0.4
platform: win10 x64

`TypeError: root.findRouters(...).getRouterInfo is not a function
    at transform (C:\Users\Administrator\AppData\Roaming\npm\node_modules\dva-cli\node_modules\dva-ast\lib\transform.js:42:32)
    at exports.default (C:\Users\Administrator\AppData\Roaming\npm\node_modules\dva-cli\node_modules\dva-ast\lib\api\index.js:46:36)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\dva-cli\lib\generate.js:92:27
    at generate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\dva-cli\lib\generate.js:108:11)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\dva-cli\bin\dva-generate:11:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)`

**Comment by sorrycc** [comment]
已知 bug 。

**Comment by arronf2e** [comment]
同碰到
node: v7.10.0
npm: v4.2.0
platform: macOs Sierra

**Comment by LukerSpringtree** [comment]
同碰到.
https://github.com/sorrycc/blog/issues/18
按照这个 来做的时候
dva g route users 会报上面的错误

node  v6.9.1
dva   v0.7.8
platform: macOs Sierra

一样的报错

**Comment by huangchaofei** [comment]
怎么解决呢  作者说一下啊。。

**Comment by OptimusYang** [comment]
@sorrycc 你好，这个问题是在解决中吗？有workaround吗？

**Comment by sorrycc** [comment]
已修复，安装最新版 dva-cli 。
