### ISSUE TITLE
Module not found: 'keymaster'

### ISSUE THREAD

**Issue by wdssss** [dvajs/dva#1105]
有两个问题.

1. Module not found: 'keymaster' , 教程里说不用做什么,会自动安装,但是我的控制台没任何反应,除了报错. 
```
   > @ build D:\code\3pp\myapp
> roadhog build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Cannot resolve module 'keymaster' in D:\code\3pp\myapp\src
```

2. styles is not defined
`Uncaught ReferenceError: styles is not defined
    at CountApp (index.js:38)
    at ReactCompositeComponent.js:305
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js:304)
    at ReactCompositeComponentWrapper._constructComponent (ReactCompositeComponent.js:279)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:187)
    at Object.mountComponent (ReactReconciler.js:45)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:370)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:257)
    at Object.mountComponent (ReactReconciler.js:45)`

**Comment by sorrycc** [comment]
看哪个教程的?

**Comment by wdssss** [comment]
https://github.com/dvajs/dva/blob/master/docs/GettingStarted.md
1. Subscribe Keyboard Event
     Here, we don't need to install keymaster dependency manually. When we write import key from 'keymaster'; and save, dva-cli will install keymaster and save to package.json. Output like this:

2. Write components

   对应这两章节

**Comment by sorrycc** [comment]
1. 工具更新过了，不会自动安装依赖了，先手动安装吧
2. styles 不存在是因为没有 `index.less` 吗?

**Comment by wdssss** [comment]
谢谢这么快回复
1. 不会更新的话,请更新文档. 我对NPM也不了解. 都不知道怎么更新呢
2. index.less存在..按照教程.也复制了对应内容

**Comment by sorrycc** [comment]
1. 执行 `npm i keymaster --save`
2. styles 的问题，方便的话把代码传到 github 上我看看

**Comment by wdssss** [comment]
代码上传了:
https://github.com/wdssss/myapp

**Comment by sorrycc** [comment]
你手动[禁用了 css modules](https://github.com/wdssss/myapp/blob/master/.roadhogrc#L3) ? ...

**Comment by StrongerSY** [comment]
你好，目前手动安装 keymaster 会有报错，如下：

Unhandled rejection RangeError: Maximum call stack size exceededill install loadIdealTree
    at RegExp.test (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/aproba/index.js:38:16
    at Array.forEach (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:33:11)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
