### ISSUE TITLE
2.0.1 版运行 dva g route 出错

### ISSUE THREAD

**Issue by questionlin** [dvajs/dva#1201]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
dva new 完项目后，执行 dva g route users，出错

#### Actual behavior: (实际效果)
dva g route users
/usr/local/lib/node_modules/dva-cli/bin/dva-generate
      create  routeComponent src/routes/Users.js, src/routes/Users.css
      create  route users with src/routes/Users.js
AssertionError [ERR_ASSERTION]: getRouterTree: component should be one of Router, Route, Redirect, IndexRedirect, IndexRoute
    at parse (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Router.js:57:28)
    at ret.children.node.children.filter.map.node (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Router.js:94:93)
    at Array.map (native)
    at parse (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Router.js:94:81)
    at NodePath.simpleMap.path (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Router.js:117:13)
    at NodePath.<anonymous> (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Helper.js:21:28)
    at __paths.forEach (/usr/local/lib/node_modules/dva-cli/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/usr/local/lib/node_modules/dva-cli/node_modules/jscodeshift/src/Collection.js:75:18)
    at Collection.simpleMap (/usr/local/lib/node_modules/dva-cli/node_modules/dva-ast/lib/collections/Helper.js:20:10)

#### Versions of packages used: (哪个库的哪个版本出现的问题)
2.0.1

**Comment by questionlin** [comment]
route.js 里面
把  <Route path="/users" component={Users} /> 放倒 <Switch/> 里面就好了

**Comment by sorrycc** [comment]
`dva g route` 暂不适用于 dva@2，感谢反馈。

**Comment by LiuSuY** [comment]
我的dva 版本是0.8.2 也同样有这个错误请问如何解决
