### ISSUE TITLE
dva结合storybook报错

### ISSUE THREAD

**Issue by JanLina** [dvajs/dva#1274]
#### Code to reproduce the issue: (代码)
```js
// BtnList/index.js
import React from 'react';
import { connect } from 'dva';
import { Button } from 'antd';
import styles from './index.css';

function Index(props) {
    return (
        <ul>
            <li><Button type="default" onClick={props.addText}>文本</Button></li>
            <li><Button type="default" onClick={props.addLike}>点赞</Button></li>
        </ul>
        )
}

function mapStateToProps(state) {
    return {
        btnList: state.btnList
    };
}

function mapDispatchToProps(dispatch) {
    return {
        addText() {
            dispatch({
                type: 'editor/addText'
            });
        },
        addLike() {
            dispatch({
                type: 'editor/addLike'
            });
        }
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(Index);
```

```js
// stories/index.js
import React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { linkTo } from '@storybook/addon-links';
import { Button, Welcome } from '@storybook/react/demo';
import BtnList from '../src/components/layouts/Toolbar/BtnList';

storiesOf('Welcome', module).add('to Storybook', () => <Welcome showApp={linkTo('Button')} />);

storiesOf('Button', module)
  .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
  .add('with some emoji', () => <Button onClick={action('clicked')}>😀 😎 👍 💯</Button>);

// 自定义组件报错
storiesOf('Layout', module)
  .add('BtnList', () => <BtnList></BtnList>);
```

#### Error
render.js:69 Invariant Violation: Could not find "store" in either the context or props of "Connect(Index)". Either wrap the root component in a &lt;Provider&gt;, or explicitly pass "store" as a prop to "Connect(Index)".
    at invariant (http://localhost:6006/static/preview.bundle.js:12310:15)
    at new Connect (http://localhost:6006/static/preview.bundle.js:110426:36)
    at http://localhost:6006/static/preview.bundle.js:63507:18
    at measureLifeCyclePerf (http://localhost:6006/static/preview.bundle.js:63288:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (http://localhost:6006/static/preview.bundle.js:63506:16)
    at ReactCompositeComponentWrapper._constructComponent (http://localhost:6006/static/preview.bundle.js:63497:19)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:6006/static/preview.bundle.js:63400:21)
    at Object.mountComponent (http://localhost:6006/static/preview.bundle.js:15483:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:6006/static/preview.bundle.js:63583:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:6006/static/preview.bundle.js:63470:21)

#### 尝试过的解决方案
查到资料说React-Redux出现此类问题，通过在外层包裹一个&lt;Provider store={store}&gt;组件就行，但是Provider貌似用于传递整个app的store给子组件，一般用来包裹最外层的容器组件；
尝试过以下解决方法，但是props.btnList作为store属性值会报错，缺乏store应有的很多属性：
```js
function Index(props) {
    return (
        <Provider store={props.btnList}>
            <ul>
                <li><Button type="default" onClick={props.addText}>文本</Button></li>
                <li><Button type="default" onClick={props.addLike}>点赞</Button></li>
            </ul>
        </Provider>
        )
}
```

#### 求解
这个问题能否通过Provider组件解决？可以的话store应该传入哪个值？

**Comment by guanrongjia** [comment]
结合 storybook，我解决了，https://blog.csdn.net/u013302113/article/details/103905750
有疑问可以交流
