### ISSUE TITLE
dva g route List throw error

### ISSUE THREAD

**Issue by chenhaifeng2016** [dvajs/dva#1321]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)

dva g route list
/usr/local/src/npm_global/lib/node_modules/dva-cli/bin/dva-generate
      create  routeComponent src/routes/List.js, src/routes/List.css
AssertionError [ERR_ASSERTION]: api/routeComponents/create: file exists
    at create (/usr/local/src/npm_global/lib/node_modules/dva-cli/node_modules/dva-ast/lib/api/routeComponents.js:34:24)
    at exports.default (/usr/local/src/npm_global/lib/node_modules/dva-cli/node_modules/dva-ast/lib/api/index.js:34:3)
    at /usr/local/src/npm_global/lib/node_modules/dva-cli/lib/generate.js:90:27
    at generate (/usr/local/src/npm_global/lib/node_modules/dva-cli/lib/generate.js:106:11)
    at Object.<anonymous> (/usr/local/src/npm_global/lib/node_modules/dva-cli/bin/dva-generate:11:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

#### Versions of packages used: (哪个库的哪个版本出现的问题)

dva-cli 0.8.2
dva 2.0.4
react 15.6.2
antd 2.13.8

**Comment by sorrycc** [comment]
`dva g` don't work with dva@2 now, we need time to improve it.
