### ISSUE TITLE
安装出错日志，什么鬼？

### ISSUE THREAD

**Issue by dachengzao** [dvajs/dva#1715]
>0 info it worked if it ends with ok
1 verbose cli [ 'E:\\station\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.6.1
3 info using node@v10.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\client\dczadmin\node_modules\.bin;C:\Users\Administrator\bin;E:\station\git\mingw64\bin;E:\station\git\usr\local\bin;E:\station\git\usr\bin;E:\station\git\usr\bin;E:\station\git\mingw64\bin;E:\station\git\usr\bin;C:\Users\Administrator\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;E:\station\Go\bin;E:\server;E:\station\go;E:\server\bin;E:\station\nodejs;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Common Files\Autodesk Shared;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;E:\station\git\cmd;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell;C:\Users\Administrator\AppData\Local\atom\bin;C:\Users\Administrator\AppData\Roaming\npm;E:\station\git\usr\bin\vendor_perl;E:\station\git\usr\bin\core_perl
10 verbose lifecycle @~start: CWD: E:\client\dczadmin
11 silly lifecycle @~start: Args: [ '/d /s /c', 'roadhog server' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `roadhog server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at EventEmitter.emit (events.js:182:13)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at ChildProcess.emit (events.js:182:13)
14 verbose stack     at maybeClose (internal/child_process.js:957:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
15 verbose pkgid @
16 verbose cwd E:\client\dczadmin
17 verbose Windows_NT 10.0.15063
18 verbose argv "E:\\station\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v10.1.0
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error @ start: `roadhog server`
23 error Exit status 1
24 error Failed at the @ start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by dachengzao** [comment]
谢谢
