### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by nsuedu** [dvajs/dva#1777]
#### 实际效果

Failed to minify the bundle. Error: index.200bdcf7.js from UglifyJs
Unexpected token: punc (() [index.200bdcf7.js:1700,13]
    at doneHandler (D:\zhixin\frontEnd\dataPlat\node_modules\af-webpack\lib\build.js:91:27)
    at emitRecords.err (D:\zhixin\frontEnd\dataPlat\node_modules\webpack\lib\Compiler.js:265:13)
    at Compiler.emitRecords (D:\zhixin\frontEnd\dataPlat\node_modules\webpack\lib\Compiler.js:371:38)
    at emitAssets.err (D:\zhixin\frontEnd\dataPlat\node_modules\webpack\lib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (D:\zhixin\frontEnd\dataPlat\node_modules\webpack\lib\Compiler.js:364:12)
    at next (D:\zhixin\frontEnd\dataPlat\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (D:\zhixin\frontEnd\dataPlat\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)

**Comment by sorrycc** [comment]
https://github.com/sorrycc/blog/issues/68

**Comment by jrschumacher** [comment]
@nsuedu I have a PR for sorrycc/roadhog#844 which supports TerserJS ([documentation](https://github.com/umijs/umi/tree/master/docs/config#minimizer))
