### ISSUE TITLE
有没有贡献文档啊

### ISSUE THREAD

**Issue by s97712** [dvajs/dva#1821]
```
$ git clone https://github.com/s97712/dva.git
$ cd dva
$ yarn
.....
$ yarn build
yarn run v1.6.0
$ node scripts/build.js
[TRANSFORM] packages/dva/src/dynamic.js
/home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/core/lib/config/full.js:127
    throw e;
    ^

Error: [BABEL] unknown: Invalid Option: browsers is not a valid top-level option.
        Maybe you meant to use 'loose'? (While processing: "/home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/preset-env/lib/index.js")
    at validateTopLevelOptions (/home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/preset-env/lib/normalize-options.js:47:13)
    at normalizeOptions (/home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/preset-env/lib/normalize-options.js:149:3)
    at _default (/home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/preset-env/lib/index.js:164:37)
    at /home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/core/lib/config/full.js:157:14)
    at cachedFunction (/home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPresetDescriptor (/home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/core/lib/config/full.js:227:63)
    at config.presets.map.descriptor (/home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/core/lib/config/full.js:72:19)
    at Array.map (<anonymous>)
    at recurseDescriptors (/home/s97712/workspace/agent-sale/packages/dva/node_modules/@babel/core/lib/config/full.js:70:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

我想要改点东西, 编译的时候报这个错误, 不知道怎么解决, 找了很久也没找到贡献文档.

**Comment by sorrycc** [comment]
是 bug，babel 相关依赖需要锁定到 46 才行。

**Comment by s97712** [comment]
能提供下解决方案吗, 我现在是直接把browsers 给删除掉了

**Comment by sorrycc** [comment]
我迟点修复下。
