### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by Hasaki1997** [dvajs/dva#1894]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
报错信息
```
$ npm start

> @ start D:\my-app\dva\dva-one
> roadhog server

'roadhog' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `roadhog server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hasaki\AppData\Roaming\npm-cache\_logs\2018-09-05T12_17_56_840Z-debug.log
```

#### Versions of packages used: (哪个库的哪个版本出现的问题)
```
$ dva -v
dva-cli version 0.9.2
    dva version 2.4.0
```
环境:win10

**Comment by Hasaki1997** [comment]
下面是报错的日志
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\software\\nodejs\\node.exe',
1 verbose cli   'D:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 info lifecycle @~start: @
7 verbose lifecycle @~start: unsafe-perm in lifecycle true
8 verbose lifecycle @~start: PATH: D:\software\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\my-app\dva\dva-quickstart3\node_modules\.bin;C:\Users\hasaki\bin;D:\software\Git\mingw64\bin;D:\software\Git\usr\local\bin;D:\software\Git\usr\bin;D:\software\Git\usr\bin;D:\software\Git\mingw64\bin;D:\software\Git\usr\bin;C:\Users\hasaki\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Sennheiser\SoftphoneSDK;D:\software\nodejs;D:\software\Git\cmd;D:\software\mipan;C:\Users\hasaki\AppData\Local\Microsoft\WindowsApps;C:\Users\hasaki\AppData\Roaming\npm;D:\software\Microsoft VS Code\bin;D:\software\Git\usr\bin\vendor_perl;D:\software\Git\usr\bin\core_perl
9 verbose lifecycle @~start: CWD: D:\my-app\dva\dva-quickstart3
10 silly lifecycle @~start: Args: [ '/d /s /c', 'roadhog server' ]
11 silly lifecycle @~start: Returned: code: 1  signal: null
12 info lifecycle @~start: Failed to exec start script
13 verbose stack Error: @ start: `roadhog server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\software\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\software\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd D:\my-app\dva\dva-quickstart3
16 verbose Windows_NT 10.0.16299
17 verbose argv "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ start: `roadhog server`
22 error Exit status 1
23 error Failed at the @ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Hasaki1997** [comment]
发现问题了,之前用公司的npm源,且换成npm后好了
