### ISSUE TITLE
项目中的 jest 使用的时候没有 jest 官方文档中的 test.each 方法

### ISSUE THREAD

**Issue by liyan-web** [dvajs/dva#1911]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
package.json:   `"test": "roadhog test"`
jest.config.js:
```
  verbose: true,
  testURL: "http://localhost/",
```
.test.js
```
describe('memberAdapter test', () => {
  test.each([members.result, 27], [[], 0])('all members', (list, length) => {
    let newList = adapter(list);
    expect(newList.length).toEqual(length);
  });
});
```
#### Expected behavior: (预期的正常效果)
测试通过或断言错误

#### Actual behavior: (实际效果)
```
TypeError: test.each is not a function

      2 | import members from "mock/allMembers";
      3 | describe('memberAdapter test', () => {
    > 4 |   test.each([members.result, 27], [[], 0])('all members', (list, length) => {
      5 |     let newList = adapter(list);
      6 |     expect(newList.length).toEqual(length);
      7 |   });

      at Suite.each (src/utils/__tests__/membersAdapter.test.js:4:8)
      at Object.describe (src/utils/__tests__/membersAdapter.test.js:3:1)
```

#### Versions of packages used: (哪个库的哪个版本出现的问题)
"roadhog": "^2.4.5",
"umi-test": "^1.0.0"

**Comment by liyan-web** [comment]
[test.each](https://jestjs.io/docs/en/api#testeachtable-name-fn-timeout)

**Comment by darylszehk01** [comment]
@liyan-web  你有找到解決方法嗎？
