### ISSUE TITLE
为什么reducers必须是 plain object or array，定义class有什么问题吗？

### ISSUE THREAD

**Issue by neoscript99** [dvajs/dva#1927]
# 错误信息
```
 [app.model] reducers should be plain object or array, but got object 
 Invariant Violation: [app.model] reducers should be plain object or array, but got object
    at invariant (http://127.0.0.1:58484/appservice/npm/invariant/invariant.js:37:15)
    at checkModel (http://127.0.0.1:58484/appservice/npm/dva-core/lib/checkModel.js:34:28)
    at Object.model (http://127.0.0.1:58484/appservice/npm/dva-core/lib/index.js:84:31)
    at http://127.0.0.1:58484/appservice/utils/dva.js:28:16
    at Array.forEach (<anonymous>)
    at Object.createApp (http://127.0.0.1:58484/appservice/utils/dva.js:27:38)
    at http://127.0.0.1:58484/appservice/app.js:33:28
    at require (http://127.0.0.1:58484/appservice/__dev__/WAService.js:23:15279)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:58484/appservice/appservice?t=1540004737691:1863:23)
```
# 代码
```
class HomeModel {
  namespace = 'home';
  state = {
    banner: [],
    brands: [],
    products_list: [],
    page: 1,
  };
  effects = new Effect();
  reducers = new Reducer();
};

class Reducer {
  save(state, {payload}) {
    return {...state, ...payload};
  }
}

class Effect {
  * load(_, {call, put}) {
    const {status, data} = yield call(homeApi.homepage, {});
    if (status === 'ok') {
      yield put({
        type: 'save', payload: {
          banner: data.banner,
          brands: data.brands
        }
      });
    }
  }

  * product(_, {call, put, select}) {
    const {page, products_list} = yield select(state => state.home);
    const {status, data} = yield call(homeApi.product, {
      page,
      mode: 1,
      type: 0,
      filter: 'sort:recomm|c:330602',
    });
    if (status === 'ok') {
      yield put({
        type: 'save', payload: {
          products_list: page > 1 ? [...products_list, ...data.rows] : data.rows,
        }
      });
    }
  }
}

export default HomeModel;
```

**Comment by lixuguang1988** [comment]
代码会报错哦，

**Comment by neoscript99** [comment]
@lixuguang1988 我这边编译是通过的，运行时报错。
你这边代码中报什么错误？

**Comment by neoscript99** [comment]
@lixuguang1988 请看下这个，能重现问题。
https://stackblitz.com/edit/dva-example-count-qga8rc

**Comment by lixuguang1988** [comment]
我的意思不要这样自定义的class的实例

**Comment by lixuguang1988** [comment]
https://github.com/dvajs/dva/issues/1930

**Comment by neoscript99** [comment]
这种Creator的方式，肯定没有类继承方便、可扩展高。
我的问题是为什么一定要限定死plain object？传new出来的实例应该也不影响框架的调用啊。

**Comment by neoscript99** [comment]
下图是README中的一个demo的代码，看下两个model的代码重复率，面向对象开发不是最好的解决办法吗？为什么不支持class呢？
https://github.com/yvanwangl/AccountSystem/blob/master/src/models/customers.js
https://github.com/yvanwangl/AccountSystem/blob/master/src/models/suppliers.js
![_code_20181109140142](https://user-images.githubusercontent.com/11485735/48245903-3c856500-e428-11e8-8198-541e9d3fbc41.png)
