### ISSUE TITLE
Failed to minify the bundle. Error: index.079c51a4.js from UglifyJs

### ISSUE THREAD

**Issue by TigerHee** [dvajs/dva#1950]
#### Code to reproduce the issue: (请提供可复现的代码或者步骤)
npm run build

#### Expected behavior: (预期的正常效果)

打包成功
#### Actual behavior: (实际效果)

Failed to compile.

Failed to minify the bundle. Error: index.079c51a4.js from UglifyJs
Unexpected token: name (matches) [index.079c51a4.js:453,5]
    at doneHandler (D:\tigerWork\b2c-moblie-v2\node_modules\_af-webpack@0.22.11@af-webpack\lib\build.js:91:27)
    at emitRecords.err (D:\tigerWork\b2c-moblie-v2\node_modules\_webpack@3.12.0@webpack\lib\Compiler.js:265:13)
    at Compiler.emitRecords (D:\tigerWork\b2c-moblie-v2\node_modules\_webpack@3.12.0@webpack\lib\Compiler.js:371:38)
    at emitAssets.err (D:\tigerWork\b2c-moblie-v2\node_modules\_webpack@3.12.0@webpack\lib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (D:\tigerWork\b2c-moblie-v2\node_modules\_webpack@3.12.0@webpack\lib\Compiler.js:364:12)
    at next (D:\tigerWork\b2c-moblie-v2\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (D:\tigerWork\b2c-moblie-v2\node_modules\_webpack@3.12.0@webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at next (D:\tigerWork\b2c-moblie-v2\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:220:14)
    at callback (D:\tigerWork\b2c-moblie-v2\node_modules\_copy-webpack-plugin@4.5.2@copy-webpack-plugin\dist\index.js:126:17)
    at Compiler.afterEmit (D:\tigerWork\b2c-moblie-v2\node_modules\_copy-webpack-plugin@4.5.2@copy-webpack-plugin\dist\index.js:220:13)
    at Compiler.applyPluginsAsyncSeries1 (D:\tigerWork\b2c-moblie-v2\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (D:\tigerWork\b2c-moblie-v2\node_modules\_webpack@3.12.0@webpack\lib\Compiler.js:361:9)
    at require.forEach.err (D:\tigerWork\b2c-moblie-v2\node_modules\_webpack@3.12.0@webpack\lib\Compiler.js:350:15)
    at D:\tigerWork\b2c-moblie-v2\node_modules\_async@2.6.1@async\dist\async.js:473:16
    at iteratorCallback (D:\tigerWork\b2c-moblie-v2\node_modules\_async@2.6.1@async\dist\async.js:1064:13)
    at D:\tigerWork\b2c-moblie-v2\node_modules\_async@2.6.1@async\dist\async.js:969:16
Read more here: http://bit.ly/2tRViJ9
#### Versions of packages used: (哪个库的哪个版本出现的问题)
不知

**Comment by jrschumacher** [comment]
@TigerHee I have a PR for sorrycc/roadhog#844 which supports TerserJS ([documentation](https://github.com/umijs/umi/tree/master/docs/config#minimizer))
