### ISSUE TITLE
简单的app.use(hooks)用法会报错

### ISSUE THREAD

**Issue by csr632** [dvajs/dva#2120]
## What happens?
使用[app.use](https://dvajs.com/api/#app-use-hooks)会报错 

## Mini Showcase Repository(REQUIRED)

https://stackblitz.com/edit/dva-use-hooks-issue

本地运行时的错误栈报告：
![image](https://user-images.githubusercontent.com/18747423/58879623-a6d55e00-8708-11e9-965b-0fffe80e0055.png)

## How To Reproduce
见stackblitz

**Expected behavior**
不报错

## Context

见stackblitz

**Comment by csr632** [comment]
在我的项目中，使用onEffect hook也会报类似的错：`TypeError: Cannot read property 'name' of undefined`

      uncaught at _callee3 at _callee3 
       at _callee6 
       at takeEvery 
       TypeError: Cannot read property 'name' of undefined
          at takeEvery (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/sagaHelpers/takeEvery.js:38:88)
          at createTaskIterator (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/proc.js:157:17)
          at runForkEffect (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/proc.js:561:24)
          at runEffect (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/proc.js:446:544)
          at next (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/proc.js:326:9)
          at proc (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/proc.js:281:3)
          at runForkEffect (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/proc.js:565:19)
          at runEffect (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/proc.js:446:544)
          at next (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/proc.js:326:9)
          at proc (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/proc.js:281:3)
          at runSaga (/Users/******/path-to-app/node_modules/redux-saga/lib/internal/runSaga.js:59:33)
          at Array.forEach (<anonymous>)
          at Object.start (/Users/******/path-to-app/node_modules/dva-core/dist/index.js:1172:11)
          at Object.start (/Users/******/path-to-app/node_modules/dva/dist/index.js:319:19)
          at start (/Users/******/path-to-app/test/index.spec.js:35:19)
          at initRiskCompWrapper (/Users/******/path-to-app/test/index.spec.js:63:34)
          at tryCatch (/Users/******/path-to-app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
          at Generator.invoke [as _invoke] (/Users/******/path-to-app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
          at Generator.prototype.(anonymous function) [as next] (/Users/******/path-to-app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
          at asyncGeneratorStep (/Users/******/path-to-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
          at _next (/Users/******/path-to-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
          at /Users/******/path-to-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
          at new Promise (<anonymous>)
          at Object.<anonymous> (/Users/******/path-to-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
          at Object.asyncJestTest (/Users/******/path-to-app/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
          at resolve (/Users/******/path-to-app/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
          at new Promise (<anonymous>)
          at mapper (/Users/******/path-to-app/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
          at promise.then (/Users/******/path-to-app/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
          at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by csr632** [comment]
应该是我的用法不对，我从app.use的文档看不出来：
onAction它自己是一个hook？还是它返回的才是hooks？（文档中说`配置 hooks 或者注册插件。（插件最终返回的是 hooks ）`）
那么onAction自己必须是一个generator function？还是它返回一个generator function?我尝试了很多种组合都不对

**Comment by LukerSpringtree** [comment]
`
 const extraMiddlewares = plugin.get('onAction');
  const middlewares = setupMiddlewares([
    promiseMiddleware,
    sagaMiddleware,
    ...flatten(extraMiddlewares),
  ]);
`

dva 中源码是这样的. 
也就说说 onAction 跟的就是 reudux 的中间件


reudux 中间件的格式形如:

`
function middleWare({getState, dispatch}){
    return function(next){
      return function(){
         //  .....
          next(action)
          //  .....
      }
   }
}
`

redux 中间件是参考 koa 来的
