### ISSUE TITLE
npm start error in osx

### ISSUE THREAD

**Issue by leinue** [dvajs/dva#239]
ERROR in ./src/index.js
Module build failed: Error: Cannot find module 'core-js/library/fn/get-iterator' (While processing preset: "/private/var/www/apache/node_modules/babel-preset-es2015/index.js")
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/var/www/apache/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-template-literals/node_modules/babel-runtime/core-js/get-iterator.js:1:93)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
 @ multi index

but, folder node_modules has  module 'core-js/library/fn/get-iterator'

**Comment by leinue** [comment]
xieyang-2:fn xieyang$ node -v
v6.6.0
xieyang-2:fn xieyang$ npm -v
3.10.3
xieyang-2:fn xieyang$ cnpm -v
4.3.2

**Comment by leinue** [comment]
@sorrycc

**Comment by sorrycc** [comment]
像是 `node_modules` 没装好，删了重装试试。

**Comment by leinue** [comment]
删了好多次重装都没用TAT @sorrycc

**Comment by sorrycc** [comment]
刚试了下没有问题。

```bash
$ dva new myapp
$ cd myapp
$ npm start
```
