### ISSUE TITLE
Invariant Violation: Could not find "store" in either the context or props

### ISSUE THREAD

**Issue by jacktang** [dvajs/dva#2420]
# 环境
 Taro 3.0.21 + dva 2.4.1

# 代码

* pages/companies/index.js
```js
import React, { useEffect } from 'react';
import { connect } from 'dva';
import { usePullDownRefresh } from '@tarojs/taro'
import { AtSearchBar, AtList, AtListItem } from 'taro-ui'
import { View, Text } from '@tarojs/components';

import "taro-ui/dist/style/components/search-bar.scss";
import "taro-ui/dist/style/components/list.scss";
import "taro-ui/dist/style/components/icon.scss";

function Index( props ) {
  const { dispatch } = props;
  useEffect(() => {
    initData();
  }, []);


  const initData = (cb) => {
    dispatch({type: 'companies/search'}).then(() => {
      cb && cb()
    })
  };

  const search = (text) => {
  };

  return (
    <>
    <AtSearchBar
      placeholder='输入公司名进行搜索'
      onChange={search}
    />
    <AtList>
      <AtListItem title='标题文字' />
      <AtListItem title='标题文字' arrow='right' />
      <AtListItem title='标题文字' extraText='详细信息' />
      <AtListItem title='禁用状态' disabled extraText='详细信息' />
    </AtList>
    </>
  )
};

function mapStateToProps(state) {
  return { ...state };
}
const IndexPage = connect(mapStateToProps)(Index);
export default IndexPage;
```

在app.js已经提供store
```js
import React, { Component } from 'react';
import { Provider } from 'react-redux';
import Taro from '@tarojs/taro';
import dva from './dva';
import models from './models';
import * as user from './utils/user';

import configStore from './store'

import './app.scss'

// const store = configStore()
const dvaApp = dva.createApp({
  initialState: {},
  models: models,
  onError(e, dispatch) {
    console.log('系统出错了!');
    // dispatch(action("sys/error", e));
  },
});
const store = dvaApp.getStore();

class App extends Component {
  componentDidMount () {}

  componentDidShow () {
    user.checkLogin().then(res => {
    }).catch(() => {
      console.log('not login');
      Taro.navigateTo({
        url: '/pages/login/index'
      });
    });
  }

  componentDidHide () {}

  componentDidCatchError () {}

  render () {
    return (
      <Provider store={store}>
        {this.props.children}
      </Provider>
    )
  }
}

export default App
```

# 错误

```
react.ts:53 Invariant Violation: Could not find "store" in either the context or props of "Connect(Index)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Index)".
    at invariant (http://127.0.0.1:19495/appservice/vendors.js:935:15)
    at new Connect (http://127.0.0.1:19495/appservice/pages/companies/index.js:5559:57)
    at Zc (http://127.0.0.1:19495/appservice/vendors.js:2164:171)
    at xe (http://127.0.0.1:19495/appservice/vendors.js:2203:149)
    at ig (http://127.0.0.1:19495/appservice/vendors.js:2281:396)
    at hg (http://127.0.0.1:19495/appservice/vendors.js:2258:22)
    at bg (http://127.0.0.1:19495/appservice/vendors.js:2257:366)
    at Of (http://127.0.0.1:19495/appservice/vendors.js:2251:214)
    at http://127.0.0.1:19495/appservice/vendors.js:2149:115
    at push../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (http://127.0.0.1:19495/appservice/vendors.js:3164:438)
```

**Comment by jacktang** [comment]
使用 class component和 @connect 是可以的
