### ISSUE TITLE
run build出现错误

### ISSUE THREAD

**Issue by wm3445** [dvajs/dva#364]
```bash
Child
    Time: 693ms
        Asset       Size  Chunks       Chunk Names
    common.js  191 bytes       0       common
    
    ERROR in ./src/index.js
    Module build failed: ReferenceError: Unknown plugin "dev-expression" specified in "base" at 3, attempted to resolve relative to "/Users/wangmeng/WebstormProjects/shanghu_zx/src"
        at /Users/wangmeng/WebstormProjects/shanghu_zx/node_modules/.6.18.2@babel-core/lib/transformation/file/options/option-manager.js:176:17
        at Array.map (native)
        at Function.normalisePlugins (/Users/wangmeng/WebstormProjects/shanghu_zx/node_modules/.6.18.2@babel-core/lib/transformation/file/options/option-manager.js:154:20)
        at OptionManager.mergeOptions (/Users/wangmeng/WebstormProjects/shanghu_zx/node_modules/.6.18.2@babel-core/lib/transformation/file/options/option-manager.js:229:36)
        at OptionManager.init (/Users/wangmeng/WebstormProjects/shanghu_zx/node_modules/.6.18.2@babel-core/lib/transformation/file/options/option-manager.js:374:12)
        at File.initOptions (/Users/wangmeng/WebstormProjects/shanghu_zx/node_modules/.6.18.2@babel-core/lib/transformation/file/index.js:216:65)
        at new File (/Users/wangmeng/WebstormProjects/shanghu_zx/node_modules/.6.18.2@babel-core/lib/transformation/file/index.js:139:24)
        at Pipeline.transform (/Users/wangmeng/WebstormProjects/shanghu_zx/node_modules/.6.18.2@babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/Users/wangmeng/WebstormProjects/shanghu_zx/node_modules/.6.2.8@babel-loader/lib/index.js:41:20)
        at /Users/wangmeng/WebstormProjects/shanghu_zx/node_modules/.6.2.8@babel-loader/lib/fs-cache.js:159:18

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build: `atool-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'atool-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     atool-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wangmeng/WebstormProjects/shanghu_zx/npm-debug.log
```

**Comment by sorrycc** [comment]
依赖没装好吧，删除 node_modules 重装依赖试试。

**Comment by wm3445** [comment]
{
  "private": true,
  "entry": {
    "index": "./src/index.js"
  },
  "dependencies": {
    "antd": "^2.5.1",
    "dva": "^1.1.0",
    "lodash": "^4.16.6",
    "qs": "^6.2.0",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-highcharts": "^11.0.0",
    "routes": "^2.1.0"
  },
  "devDependencies": {
    "atool-build": "^0.9.0",
    "babel-eslint": "^6.0.4",
    "babel-plugin-dva-hmr": "^0.2.0",
    "babel-plugin-import": "^1.0.1",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-runtime": "^6.9.2",
    "dora": "0.3.x",
    "dora-plugin-proxy": "^0.7.0",
    "dora-plugin-webpack": "0.6.x",
    "dora-plugin-webpack-hmr": "^0.1.0",
    "eslint": "^2.13.1",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-plugin-import": "^1.8.1",
    "eslint-plugin-jsx-a11y": "^1.4.2",
    "eslint-plugin-react": "^5.1.1",
    "glob": "^7.0.5",
    "mockjs": "^1.0.1-beta2",
    "redbox-react": "^1.2.10"
  },
  "scripts": {
    "start": "dora --plugins \"proxy,webpack,webpack-hmr\"",
    "lint": "eslint --fix --ext .js,.jsx .",
    "build": "atool-build"
  },
  "theme": "./theme.js"
}

这是我的package

**Comment by sorrycc** [comment]
webpack.config.js 里把 dev-expression 相关的语句删了。

**Comment by wm3445** [comment]
@sorrycc 谢了 ，删除后可以build了
