### ISSUE TITLE
构建失败, 看不出什么问题啊!

### ISSUE THREAD

**Issue by ityao** [dvajs/dva#387]
bogon:admin silver$ npm start

> @ start /Users/silver/program/grandhope/admin
> dora --plugins "proxy,webpack,webpack-hmr"

          proxy: load rule from proxy.config.js
(node:43886) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8989
📦  2/3 build modulesYou are using prebuilt antd,
please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.
📦  15/16 build modules
webpack: bundle build is now finished.
Hash: 7c803b01a360be7eb727
Version: webpack 1.12.15
Time: 1469ms
    Asset     Size  Chunks             Chunk Names
common.js  24.3 kB       0  [emitted]  common
 index.js  84.2 kB    1, 0  [emitted]  index
chunk    {0} common.js (common) 0 bytes [rendered]
chunk    {1} index.js (index) 78.4 kB {0} [rendered]
    [0] multi index 40 bytes {1} [built] [1 error]
    [1] ./~/.1.2.0@html-entities/lib/html5-entities.js 49 kB {1} [built]
    [2] ./~/.0.0.6@ansi-html/index.js 4.26 kB {1} [built]
    [3] ./~/.0.2.0@querystring/decode.js 2.4 kB {1} [built]
    [4] ./~/.0.2.0@querystring/encode.js 2.09 kB {1} [built]
    [5] ./~/.0.2.0@querystring/index.js 127 bytes {1} [built]
    [6] (webpack)/buildin/module.js 251 bytes {1} [built]
    [7] ./~/.1.2.0@html-entities/index.js 231 bytes {1} [built]
    [8] ./~/.1.2.0@html-entities/lib/html4-entities.js 6.57 kB {1} [built]
    [9] ./~/.1.2.0@html-entities/lib/xml-entities.js 2.98 kB {1} [built]
   [10] ./~/.2.0.0@ansi-regex/index.js 135 bytes {1} [built]
   [11] ./~/.2.13.2@webpack-hot-middleware/client-overlay.js 1.74 kB {1} [built]
   [12] ./~/.2.13.2@webpack-hot-middleware/client.js?path=http%3A%2F%2F127.0.0.1%3A8000%2F__webpack_hmr&reload=true 4.6 kB {1} [built]
   [13] ./~/.2.13.2@webpack-hot-middleware/process-update.js 3.88 kB {1} [built]
   [14] ./~/.3.0.1@strip-ansi/index.js 161 bytes {1} [built]

ERROR in ./src/index.js
Module build failed: TypeError: Plugin 3 specified in "base" was expected to return a function but returned "undefined"
    at Function.normalisePlugin (/Users/silver/program/grandhope/admin/node_modules/.6.20.0@babel-core/lib/transformation/file/options/option-manager.js:144:15)
    at /Users/silver/program/grandhope/admin/node_modules/.6.20.0@babel-core/lib/transformation/file/options/option-manager.js:180:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/silver/program/grandhope/admin/node_modules/.6.20.0@babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/silver/program/grandhope/admin/node_modules/.6.20.0@babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/silver/program/grandhope/admin/node_modules/.6.20.0@babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/silver/program/grandhope/admin/node_modules/.6.20.0@babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/silver/program/grandhope/admin/node_modules/.6.20.0@babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/silver/program/grandhope/admin/node_modules/.6.20.0@babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/silver/program/grandhope/admin/node_modules/.6.2.9@babel-loader/lib/index.js:41:20)
 @ multi index

**Comment by ityao** [comment]
把webpack.config.js里面的
//webpackConfig.babel.plugins.push(['antd', {style: 'css'}]);
注释掉就好了, 可出现了奇怪的warning
(node:44911) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by sorrycc** [comment]
npm 啥版本?

**Comment by ityao** [comment]
bogon:admin silver$ node -v
v7.2.1
bogon:admin silver$ npm -v
3.10.10

**Comment by sorrycc** [comment]
babel-plugin-antd 已改名为 babel-plugin-import，如果你用 antd，换下试试。https://ant.design/docs/react/practical-projects-cn#使用-antd
