### ISSUE TITLE
Caught exception: Error: listen EADDRINUSE :::8989

### ISSUE THREAD

**Issue by summerinsect** [dvajs/dva#425]
启动不了了
```javascript
$ npm start

> @ start C:\Users\Administrator\workspace\dva-new-web
> dora --plugins "proxy?watchDirs=./mock,webpack,webpack-hmr"

          proxy: load rule from proxy.config.js
(node:5452) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8989
Caught exception: Error: listen EADDRINUSE :::8989
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at C:\Users\Administrator\workspace\dva-new-web\node_modules\dora-plugin-proxy\node_modules\dora-anyproxy\proxy.js:125:38
    at C:\Users\Administrator\workspace\dva-new-web\node_modules\dora-plugin-proxy\node_modules\dora-anyproxy\node_modules\async\lib\async.js:607:21
    at C:\Users\Administrator\workspace\dva-new-web\node_modules\dora-plugin-proxy\node_modules\dora-anyproxy\node_modules\async\lib\async.js:246:17
    at iterate (C:\Users\Administrator\workspace\dva-new-web\node_modules\dora-plugin-proxy\node_modules\dora-anyproxy\node_modules\async\lib\async.js:146:13)
    at C:\Users\Administrator\workspace\dva-new-web\node_modules\dora-plugin-proxy\node_modules\dora-anyproxy\node_modules\async\lib\async.js:157:25
AnyProxy is about to exit with code: 0
```

**Comment by summerinsect** [comment]
端口被占用了 #369
