### ISSUE TITLE
升级1.2后，开发中的项目彻底用不了了：app.model: namespace should be unique

### ISSUE THREAD

**Issue by longzb** [dvajs/dva#465]
请问下，目前有好的方法解决吗？？
我喊了几个同事核实几遍了并没有重复的namespace啊！！
```
uncaught at _callee3 
 at _callee6 
 at takeEvery(analyze/query, _callee) 
 at _callee 
 at _callee 
 Error: Invariant Violation: app.model: namespace should be unique
    at invariant (http://localhost:8000/index.js:14900:16)
    at checkModel (http://localhost:8000/index.js:22389:32)
    at Object.injectModel (http://localhost:8000/index.js:22095:12)
    at http://localhost:8000/index.js:55300:18
    at http://localhost:8000/index.js:136:24
    at Function.requireEnsure [as e] (http://localhost:8000/index.js:597:29)
    at Function.ensure [as e] (http://localhost:8000/index.js:134:33)
    at Object.getComponent (http://localhost:8000/index.js:55299:32)
    at getComponentsForRoute (http://localhost:8000/index.js:17508:17)
    at http://localhost:8000/index.js:17520:6
    at http://localhost:8000/index.js:22197:16
    at http://localhost:8000/index.js:28091:27
    at onErrorWrapper (http://localhost:8000/index.js:22202:12)
    at sagaWithCatch$ (http://localhost:8000/index.js:22561:18)
    at tryCatch (http://localhost:8000/index.js:20492:41)
    at Generator.invoke [as _invoke] (http://localhost:8000/index.js:20783:23)
    at Generator.prototype.(anonymous function) [as throw] (http://localhost:8000/index.js:20544:22)
    at next (http://localhost:8000/index.js:26239:33)
    at Object.currCb [as cont] (http://localhost:8000/index.js:26338:8)
    at end (http://localhost:8000/index.js:26305:24)
```

**Comment by sorrycc** [comment]
多次用 app.model 注册了同一个 namespace 的 model ?

**Comment by longzb** [comment]
@sorrycc  确定没有，我开始也怀疑在路由里动态注册重复的了，但我一个一个的看的确没有重复注册的，之前1.1都正常的，就是把node_modules删除后，重新npm install后就出现这个问题了。

**Comment by longzb** [comment]
@sorrycc 我访问的路由没有注册的model可以正常，第一次访问有动态加载model的就报不唯一的错误

**Comment by longzb** [comment]
@sorrycc 我切换会1.1.0就一切正常了，不知道1.1.0版本的跟vue-cli最新用roadhogrc那种配合有没有问题，没的话就用1.1算了。

**Comment by sorrycc** [comment]
给个能重现的 repo ?

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues/460#issuecomment-270417395，这个能解决你的问题吗?

**Comment by kulwe** [comment]
![_20170106142007](https://cloud.githubusercontent.com/assets/1769161/21709352/57d895ee-d41b-11e6-9494-0758e89a2b99.png)
用WeakMap简单处理一下，不要直接用app.model。  App.attachedModels=new WeakMap;

**Comment by nianhua110** [comment]
#502 
我在这儿写了一种方式，不知道行不行。

**Comment by sorrycc** [comment]
对动态加载的问题总结了下，有问题在 #533 里跟进。
