### ISSUE TITLE
在user-dashbord这个例子里面有错误

### ISSUE THREAD

**Issue by golden-hu** [dvajs/dva#62]
将源码下载之后：
npm install
npm start
之后提示出错：

```bash
ERROR in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/hugo/Documents/workspace/react/dva-master/.babelrc" at 0, attempted to resolve relative to "/Users/hugo/Documents/workspace/react/dva-master"
    at /Users/hugo/Documents/workspace/react/dva-master/examples/user-dashboard/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/hugo/Documents/workspace/react/dva-master/examples/user-dashboard/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/Users/hugo/Documents/workspace/react/dva-master/examples/user-dashboard/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/Users/hugo/Documents/workspace/react/dva-master/examples/user-dashboard/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
    at File.initOptions (/Users/hugo/Documents/workspace/react/dva-master/examples/user-dashboard/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/hugo/Documents/workspace/react/dva-master/examples/user-dashboard/node_modules/babel-core/lib/transformation/file/index.js:137:24)
    at Pipeline.transform (/Users/hugo/Documents/workspace/react/dva-master/examples/user-dashboard/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/hugo/Documents/workspace/react/dva-master/examples/user-dashboard/node_modules/babel-loader/index.js:38:20)
    at /Users/hugo/Documents/workspace/react/dva-master/examples/user-dashboard/node_modules/babel-loader/lib/fs-cache.js:145:18
 @ multi index
```

**Comment by sorrycc** [comment]
试试 npm3 或者 [npminstall](https://github.com/cnpm/npminstall)

**Comment by golden-hu** [comment]
XinghuaHudeMacBook-Pro:user-dashboard hugo$ npm -v
3.10.3
我的已经是npm3了
另外我删除node-modules这个目录中的所有文 件
重新npm install
之后，还是报这个错误

**Comment by sorrycc** [comment]
dva-master 里也 npm install 试试?

**Comment by golden-hu** [comment]
dva-master中npm install之后，再回到user-bashboard之后再npm start可以正常启动了。
再请问，为什么需要在dva-master中安装呢，还不是在user-bashboard中？

**Comment by sorrycc** [comment]
应该是 babel-loader 会往上找 babelrc 引起的，之后会修复这个问题。

**Comment by bryt-li** [comment]
现在example下的user-dashboard例子不会出错了，但是其它例子都报同样错误。
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/foo/Code/dva/.babelrc" at 0, attempted to resolve relative to "/Users/foo/Code/dva"
babel-loader 会往上找 babelrc。

**Comment by sorrycc** [comment]
先在 dva 目录下 `npm install` 安装依赖。

**Comment by jozhi** [comment]
`
ERROR in /Users/jozhi-pc/Downloads/dva-master/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib in /Users/jozhi-pc/Downloads/dva-master
 @ /Users/jozhi-pc/Downloads/dva-master/index.js 7:18-34

ERROR in /Users/jozhi-pc/Downloads/dva-master/src/index.js
Module not found: Error: Cannot resolve module 'babel' in /Users/jozhi-pc/Downloads/dva-master/src
 @ /Users/jozhi-pc/Downloads/dva-master/src/index.js 13:17-39
`
很奇怪
