### ISSUE TITLE
dva 不能兼容百度编码的链接，报错

### ISSUE THREAD

**Issue by kenan2002** [dvajs/dva#876]
dva 版本 1.2.1

百度编码中文是按照 GBK 编码的，而 history 2.x 所依赖的 query-string 3.x 里使用了 decodeURIComponent 来解码 URI，它遇到非 UTF8 编码时会出错

比如 https://bearychat.com/?from=baidu-一熊科技 会被编码为 https://bearychat.com/?from=baidu-%D2%BB%D0%DC%BF%C6%BC%BC 导致 history 里 decodeURIComponent 的时候出错

```
index.js:30 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at https://bearychat.com/static/js/main.b774328f.js:8:8512
    at Array.reduce (native)
    at t.parse (https://bearychat.com/static/js/main.b774328f.js:8:8360)
    at t (https://bearychat.com/static/js/main.b774328f.js:1:31725)
    at https://bearychat.com/static/js/main.b774328f.js:2:150
    at https://bearychat.com/static/js/main.b774328f.js:5:29170
    at https://bearychat.com/static/js/main.b774328f.js:5:25871
    at Array.forEach (native)
    at n (https://bearychat.com/static/js/main.b774328f.js:5:25851)
```

所以能不能升级 react-router 的版本呢，不然这个 bug 绕不过去

**Comment by zjxpcyc** [comment]
可以跳过去，不用 history , 用 window.location

**Comment by kenan2002** [comment]
@zjxpcyc 
谢谢你的建议。报错是从百度跳转到我的网站，不是从我的网站跳转。
