### ISSUE TITLE
代理规则bug？

### ISSUE THREAD

**Issue by zpz1982** [dvajs/dva#93]
根据文档，对于
` 'GET /api/(.*)': 'http://foo.com/'`

如果请求是 /api/rest/test/1, 
那么应该转发到 http://foo.com/rest/test/1
但是现在实际情况是被转发到 http://foo.com/api/rest/test/1

**Comment by sorrycc** [comment]
https://github.com/dora-js/dora-plugin-proxy/pull/94

**Comment by sorrycc** [comment]
把 `GET` 去掉，或者等下个小版本修复。

**Comment by sorrycc** [comment]
已修复，升级到 dora-plugin-proxy@0.8.2

**Comment by zpz1982** [comment]
升级到0.8.2 以后会报错：

Caught exception: TypeError: proxyConfig is not a function
    at replacePath (D:\git\dvatest\node_modules\.npminstall\dora-plugin-proxy\0.8.2\dora-plugin-proxy\lib\rule.js:97:49)
    at setOption (D:\git\dvatest\node_modules\.npminstall\dora-plugin-proxy\0.8.2\dora-plugin-proxy\lib\rule.js:115:26)
    at D:\git\dvatest\node_modules\.npminstall\dora-plugin-proxy\0.8.2\dora-plugin-proxy\lib\rule.js:125:11
    at batchMatch (D:\git\dvatest\node_modules\.npminstall\dora-plugin-proxy\0.8.2\dora-plugin-proxy\lib\rule.js:198:22)
    at Object.replaceRequestOption (D:\git\dvatest\node_modules\.npminstall\dora-plugin-proxy\0.8.2\dora-plugin-proxy\lib\rule.js:121:7)
    at dealWithRemoteResonse (D:\git\dvatest\node_modules\.npminstall\dora-anyproxy\3.8.4\dora-anyproxy\lib\requestHandler.js:132:28)
    at routeReq (D:\git\dvatest\node_modules\.npminstall\dora-anyproxy\3.8.4\dora-anyproxy\lib\requestHandler.js:89:13)
    at D:\git\dvatest\node_modules\.npminstall\async\0.9.2\async\lib\async.js:607:21
    at D:\git\dvatest\node_modules\.npminstall\async\0.9.2\async\lib\async.js:246:17
    at iterate (D:\git\dvatest\node_modules\.npminstall\async\0.9.2\async\lib\async.js:146:13)

安装最新的dora 0.4.3以后，甚至无法启动dva了

**Comment by sorrycc** [comment]
我试着把 dva-cli 的依赖升级到最新，没有发现问题。https://github.com/dvajs/dva-cli/commit/1eb633fda8fd9de8e5e5a3b425c3f9b99c8ba6bb

把你的 proxy.config.js 贴出来看下。

**Comment by zpz1982** [comment]
就一条规则
`'/api/(.*)': 'http://dashboard.yrs.amd.com:9090/',`

按照你的更新，包全部升级以后，dva可以启动了，但是只要触发那个规则就会报错。似乎是dora-anyproxy出来问题，是不是也要更新了

**Comment by sorrycc** [comment]
0.8.2 确实有问题，https://github.com/dora-js/dora-plugin-proxy/pull/94/files#r79535512

**Comment by sorrycc** [comment]
dora-plugin-proxy@0.8.3
